"""Mera Mera no Mi — flame fruit (Phase 2).

Real flames, not a colour tint. This is the classic DOOM/Amiga "fire palette"
simulation: keep a small grid of heat values, let heat rise and decay each
frame, then map heat through a black→red→orange→yellow→white gradient. A handful
of NumPy ops, runs comfortably in real time, and reads like fire rather than
particles.

The fire is seeded two ways so it looks generated by the body:
* a flickering hot row along the bottom of the body silhouette, and
* hot blobs at the hands, so flames stream off your palms.

It's then masked to a *dilated* body outline so flames lick outward past the
edges instead of stopping at a hard silhouette.
"""

from __future__ import annotations

from typing import Optional, Tuple

import cv2
import numpy as np

from effects._blend import screen
from effects.base import BaseEffect
from utils import gesture
from utils.tracking import Tracking

DOWNSCALE = 3          # heat grid is 1/DOWNSCALE of the frame (speed)
COOLING = 0.985        # multiplicative heat retention per frame
DECAY = 0.045          # random additional cooling, per cell per frame


def _build_palette() -> np.ndarray:
    """256-entry BGR fire LUT, black at 0 → white at 255."""
    stops = [  # (heat 0..1, B, G, R)
        (0.00, 0, 0, 0),
        (0.25, 0, 0, 110),
        (0.45, 10, 40, 210),
        (0.62, 20, 130, 255),
        (0.80, 130, 230, 255),
        (1.00, 255, 255, 255),
    ]
    xs = np.linspace(0.0, 1.0, 256)
    pts = np.array([s[0] for s in stops])
    lut = np.zeros((256, 3), np.uint8)
    for ch in range(3):
        vals = np.array([s[ch + 1] for s in stops])
        lut[:, ch] = np.clip(np.interp(xs, pts, vals), 0, 255).astype(np.uint8)
    return lut


class MeraMera(BaseEffect):
    name = "Mera Mera"
    swatch = (20, 90, 240)  # fiery orange-red (BGR)
    requires = {"mask", "hands"}

    def __init__(self):
        self._palette = _build_palette()
        self._heat: Optional[np.ndarray] = None
        self._size: Optional[Tuple[int, int]] = None  # (gh, gw)

    def reset(self) -> None:
        self._heat = None  # cold start next activation

    def _ensure_grid(self, w: int, h: int) -> None:
        gh, gw = h // DOWNSCALE, w // DOWNSCALE
        if self._heat is None or self._size != (gh, gw):
            self._heat = np.zeros((gh, gw), np.float32)
            self._size = (gh, gw)

    def _seed(self, lm: Tracking, mask_small: Optional[np.ndarray]) -> None:
        gh, gw = self._size
        heat = self._heat

        # Flickering hot baseline along the bottom couple of rows.
        flicker = np.random.rand(gw).astype(np.float32)
        heat[gh - 1, :] = np.maximum(heat[gh - 1, :], 0.6 + 0.4 * flicker)

        # If we have a mask, also ignite the lowest occupied row of each column
        # so the body itself catches rather than only the frame bottom.
        if mask_small is not None:
            cols = np.where(mask_small > 0.5)
            if cols[0].size:
                # bottom-most row per occupied column
                ys, xs = cols
                order = np.lexsort((-ys, xs))
                xs_o, ys_o = xs[order], ys[order]
                first = np.concatenate(([True], xs_o[1:] != xs_o[:-1]))
                bx, by = xs_o[first], ys_o[first]
                heat[by, bx] = np.maximum(heat[by, bx], 0.85)

        # Hot blobs at the hands → flames stream off the palms.
        for hand in lm.hands:
            p = gesture.pinch_point(hand.landmarks, lm.w, lm.h) / DOWNSCALE
            cx, cy = int(p[0]), int(p[1])
            r = max(2, gw // 30)
            y0, y1 = max(0, cy - r), min(gh, cy + r + 1)
            x0, x1 = max(0, cx - r), min(gw, cx + r + 1)
            heat[y0:y1, x0:x1] = np.maximum(heat[y0:y1, x0:x1], 0.95)

    def _propagate(self) -> None:
        heat = self._heat
        rising = np.roll(heat, -1, axis=0)          # pull heat up from the row below
        rising[-1, :] = heat[-1, :]                 # bottom keeps its seed
        rising = cv2.blur(rising, (3, 1))           # slight horizontal spread (wind)
        decay = np.random.rand(*heat.shape).astype(np.float32) * DECAY
        self._heat = np.clip(rising * COOLING - decay, 0.0, 1.0)

    def process_frame(self, frame: np.ndarray, landmarks: Tracking,
                      mask: Optional[np.ndarray], t: float) -> np.ndarray:
        h, w = frame.shape[:2]
        self._ensure_grid(w, h)
        gh, gw = self._size

        mask_small = None
        if mask is not None:
            mask_small = cv2.resize(mask, (gw, gh), interpolation=cv2.INTER_LINEAR)

        self._seed(landmarks, mask_small)
        self._propagate()

        # Heat grid → coloured fire at full resolution.
        idx = np.clip(self._heat * 255.0, 0, 255).astype(np.uint8)
        fire_small = self._palette[idx]                       # (gh, gw, 3) BGR
        fire = cv2.resize(fire_small, (w, h), interpolation=cv2.INTER_LINEAR)

        # Confine flames to a dilated body region so they hug the person but
        # still lick outward past the silhouette.
        if mask is not None:
            gate = cv2.dilate((mask > 0.3).astype(np.uint8),
                              np.ones((25, 25), np.uint8))
            gate = cv2.GaussianBlur(gate.astype(np.float32), (31, 31), 0)[:, :, None]
            fire = (fire.astype(np.float32) * np.clip(gate, 0, 1)).astype(np.uint8)

        return screen(frame, fire)
